"""
Dynamic-landing generator — the "content-linked dynamic landing" building block.

Reads data/dynamic.json (spec: data/dynamic.schema.json), and for every `active`
landing emits a page fragment + head sidecar into src/<lang>/dynamic/<slug>.html.
Then build.py assembles them into en/dynamic/<slug>.html.

This is the reusable pattern: ONE template (below), MANY data entries, produced by
content-factory and consumed here. To add a landing, content-factory adds an entry
to the manifest — no HTML is hand-written.

  Workflow:
    python scripts/generate_dynamic_pages.py     # data -> src/<lang>/dynamic/*.html
    python build.py --env staging                # src -> en/dynamic/*.html

Per ad, only three slots change: the hero image (the creative), the headline, and
the subtext. Everything else is shared boilerplate owned here.
"""

import json
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = ROOT / "data" / "dynamic.json"
SRC = ROOT / "src"

# Marks generated files so a future clean step can remove stale pages safely.
GEN_MARKER = "<!-- generated by scripts/generate_dynamic_pages.py — do not edit by hand -->"


def aspect_css(value: str) -> str:
    v = (value or "1:1").replace(" ", "")
    if ":" in v:
        w, h = v.split(":", 1)
        return f"{w} / {h}"
    return "1 / 1"


def esc_attr(s: str) -> str:
    return (str(s or "")
            .replace("&", "&amp;").replace('"', "&quot;")
            .replace("<", "&lt;").replace(">", "&gt;"))


def build_cta_href(cta: dict, utm: dict) -> str:
    href = cta.get("href") or "{{app_base}}/en/enroll"
    parts = []
    for key in ("source", "medium", "campaign", "content", "term"):
        val = (utm or {}).get(key)
        if val:
            parts.append(f"utm_{key}={quote(str(val))}")
    if parts:
        href += ("&" if "?" in href else "?") + "&".join(parts)
    return href


HEAD_CSS = """<style>
  /* Dynamic ad-matched landing — shared styles for the building block.
     Warm + light; navy ink, teal accent. Generated; edit the generator, not this. */
  .adl-main { padding: 0 !important; max-width: none !important; }
  .adl-page {
    --adl-ink: var(--primary-dk, #1B3A5C);
    --adl-muted: var(--text-muted, #5b6b7a);
    --adl-border: var(--border, #e4e8ee);
    --adl-accent: var(--accent, #2BB6A3);
    font-family: 'DM Sans', system-ui, sans-serif;
    color: var(--adl-ink);
  }
  .adl-hero { background: linear-gradient(180deg, #FBF7EF 0%, #F3EFE6 100%); padding: 64px 22px; }
  .adl-hero-grid {
    max-width: 1080px; margin: 0 auto;
    display: grid; grid-template-columns: 1.05fr 0.95fr; gap: 48px; align-items: center;
  }
  .adl-hero-text { min-width: 0; }
  .adl-h1 { font-weight: 700; font-size: clamp(2rem, 4.4vw, 3.1rem); line-height: 1.1; margin: 0 0 18px; color: var(--adl-ink); }
  .adl-h1 em { font-style: normal; color: var(--adl-accent); }
  .adl-sub { font-size: 1.15rem; line-height: 1.55; color: var(--adl-muted); margin: 0 0 28px; max-width: 460px; }
  .adl-sub em { font-style: italic; color: var(--adl-ink); }
  .adl-cta {
    display: inline-block; padding: 16px 32px; border-radius: 14px;
    background: var(--adl-accent); color: #fff; font-weight: 700; font-size: 1.1rem;
    text-decoration: none; box-shadow: 0 6px 20px rgba(43, 182, 163, 0.28);
    transition: transform .12s ease, box-shadow .12s ease;
  }
  .adl-cta:hover, .adl-cta:focus { transform: translateY(-2px); color: #fff; box-shadow: 0 10px 26px rgba(43, 182, 163, 0.36); }
  .adl-note { margin: 14px 0 0; font-size: .9rem; color: var(--adl-muted); }
  .adl-hero-media { display: flex; justify-content: center; }
  /* Filled creative: framed, shown in full (no crop). */
  .adl-adframe {
    width: 100%; max-width: 440px; background: #fff; border-radius: 20px; overflow: hidden;
    border: 1px solid var(--adl-border); box-shadow: 0 8px 28px rgba(27, 58, 92, 0.10);
  }
  .adl-adframe img { width: 100%; height: 100%; object-fit: contain; display: block; }
  /* Empty slot: placeholder for the template view. */
  .adl-adslot {
    width: 100%; max-width: 440px; aspect-ratio: 1 / 1; background: #fff;
    border: 2px dashed var(--adl-accent); border-radius: 20px;
    display: flex; flex-direction: column; align-items: center; justify-content: center;
    gap: 10px; text-align: center; padding: 24px; box-shadow: 0 8px 28px rgba(27, 58, 92, 0.08);
  }
  .adl-adslot-ico { font-size: 2.4rem; opacity: .8; }
  .adl-adslot-label { font-weight: 700; font-size: 1.05rem; letter-spacing: .08em; color: var(--adl-ink); }
  .adl-adslot-dims { font-size: .85rem; color: var(--adl-muted); max-width: 240px; }
  @media (max-width: 760px) {
    .adl-hero { padding: 44px 20px; }
    .adl-hero-grid { grid-template-columns: 1fr; gap: 30px; }
    .adl-hero-media { order: -1; }
    .adl-adslot, .adl-adframe { max-width: 360px; }
  }
</style>
"""

ATTR_SCRIPT = """<script>
  // Preserve the ad's source/campaign through to enroll for attribution.
  (function () {
    var p = new URLSearchParams(window.location.search);
    var source = (p.get('utm_source') || p.get('src') || 'ad').toLowerCase();
    window.dataLayer = window.dataLayer || [];
    window.dataLayer.push({ event: 'dynamic_landing_view', link_source: source, landing: '__SLUG__' });
    document.querySelectorAll('[data-cta]').forEach(function (a) {
      a.addEventListener('click', function () {
        window.dataLayer.push({ event: 'dynamic_cta_click', link_source: source, link_destination: a.getAttribute('data-dest') });
      });
    });
  })();
</script>
"""


def media_block(hero: dict) -> str:
    image = hero.get("image")
    if image:
        ratio = aspect_css(hero.get("aspect"))
        alt = esc_attr(hero.get("image_alt", ""))
        return (
            '<div class="adl-hero-media">\n'
            f'        <div class="adl-adframe" style="aspect-ratio: {ratio};">\n'
            f'          <img src="{esc_attr(image)}" alt="{alt}" '
            'onerror="this.onerror=null;this.src=\'/en/static/images/mitra-logo-icon-v2_003.png\';this.style.objectFit=\'contain\';this.style.padding=\'26%\';this.style.opacity=\'.5\';">\n'
            '        </div>\n'
            '      </div>'
        )
    return (
        '<div class="adl-hero-media">\n'
        '        <div class="adl-adslot" role="img" aria-label="Ad creative placeholder">\n'
        '          <span class="adl-adslot-ico">&#128247;</span>\n'
        '          <span class="adl-adslot-label">AD CREATIVE</span>\n'
        '          <span class="adl-adslot-dims">the exact graphic from the ad goes here</span>\n'
        '        </div>\n'
        '      </div>'
    )


def render_page(entry: dict) -> str:
    hero = entry.get("hero", {})
    cta = entry.get("cta", {})
    meta = entry.get("meta", {})
    slug = entry["slug"]

    cta_href = build_cta_href(cta, entry.get("utm", {}))
    title = meta.get("title", "Mitra — start your free trial").replace("\n", " ")
    desc = meta.get("description", "").replace("\n", " ")

    text_block = (
        '<div class="adl-hero-text">\n'
        f'        <h1 class="adl-h1">{hero.get("headline_html", "")}</h1>\n'
        f'        <p class="adl-sub">{hero.get("subtext_html", "")}</p>\n'
        f'        <a class="adl-cta" href="{cta_href}" data-cta data-dest="hero">{esc_attr(cta.get("label", "Start your 7-day free trial"))}</a>\n'
        '        <p class="adl-note">No app to install &middot; works on the chat apps you already use</p>\n'
        '      </div>'
    )

    page = f"""<!-- META
title: {title}
description: {desc}
slug: dynamic/{slug}.html
main_class: adl-main
og_description: {desc}
-->
{GEN_MARKER}
<div class="adl-page">
  <section class="adl-hero">
    <div class="adl-hero-grid">
      {text_block}
      {media_block(hero)}
    </div>
  </section>
</div>
{ATTR_SCRIPT.replace("__SLUG__", slug)}"""
    return page


def main() -> int:
    if not DATA_PATH.exists():
        print(f"ERROR: {DATA_PATH} not found", file=sys.stderr)
        return 1
    data = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    landings = data.get("landings", [])

    written = 0
    seen = set()
    for entry in landings:
        if entry.get("status") != "active":
            continue
        slug = entry.get("slug")
        lang = entry.get("lang", "en")
        if not slug:
            print("WARNING: skipping entry with no slug", file=sys.stderr)
            continue
        key = (lang, slug)
        if key in seen:
            print(f"ERROR: duplicate slug '{slug}' for lang '{lang}'", file=sys.stderr)
            return 1
        seen.add(key)

        out_dir = SRC / lang / "dynamic"
        out_dir.mkdir(parents=True, exist_ok=True)
        (out_dir / f"{slug}.html").write_text(render_page(entry), encoding="utf-8")
        (out_dir / f"{slug}.head.html").write_text(HEAD_CSS, encoding="utf-8")
        written += 1
        print(f"  wrote src/{lang}/dynamic/{slug}.html (+ .head.html)")

    print(f"Generated {written} dynamic landing page(s). Next: python build.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
